source "https://rubygems.org"

gem "chef", "12.3.0"
gem "berkshelf", github: "berkshelf/berkshelf"
gem "test-kitchen"
gem "knife-solo"
gem "knife-ec2"
gem "thor"
gem "rubocop"
gem "colorize"
gem "capistrano"
gem "ipaddress"
