name             'docker-couchbase'
maintainer       'Ride Share Market'
maintainer_email 'systemsadmin@ridesharemarket.com'
license          'All rights reserved'
description      'Installs/Configures docker-couchbase'
long_description 'Installs/Configures docker-couchbase'
version          '0.1.0'

depends 'docker'
depends 'secrets'