name             'docker-jenkins'
maintainer       'Ride Share Market'
maintainer_email 'systemsadmin@ridesharemarket.com'
license          'All rights reserved'
description      'Installs/Configures docker-jenkins'
long_description 'Installs/Configures docker-jenkins'
version          '1.0.0'

depends 'docker'
depends 'secrets'