name             'docker-relk'
maintainer       'Ride Share Market'
maintainer_email 'systemsadmin@ridesharemarket.com'
license          'All rights reserved'
description      'Installs/Configures docker-relk'
long_description 'Installs/Configures docker-relk'
version          '1.0.1'

depends 'docker'
depends 'secrets'
depends 'docker-lumberjack'
