name             'netdata'
maintainer       'Ride Share Market'
maintainer_email 'systemsadmin@ridesharemarket.com'
license          'All rights reserved'
description      'Installs/Configures netdata'
long_description 'Installs/Configures netdata'
version          '1.0.1'
