# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  # config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  # config.vm.box = "trustytahr"
  config.vm.box = "file://#{__dir__}/tmp/trustytahr_2015-08-31.box"

  config.vm.define "cis" do |cis|
    cis.vm.network "private_network", ip: "192.168.33.100"
    cis.ssh.forward_agent = true
    cis.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.name = "cis01.dev.vbx.ridesharemarket.com"
    end
  end

  config.vm.define "app" do |app|
    app.vm.network "private_network", ip: "192.168.33.101"
    app.ssh.forward_agent = true
    app.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "app01.dev.vbx.ridesharemarket.com"
    end
  end

end
