name             'docker-scripts'
maintainer       'Ride Share Market'
maintainer_email 'systemsadmin@ridesharemarket.com'
license          'All rights reserved'
description      'Installs/Configures docker-scripts'
long_description 'Installs/Configures docker-scripts'
version          '1.0.2'
