name             'firehol'
maintainer       'Ride Share Market'
maintainer_email 'systemsadmin@ridesharemarket.com'
license          'All rights reserved'
description      'Installs/Configures firehol'
long_description 'Installs/Configures firehol'
version          '1.0.0'

depends 'secrets'
depends 'logrotate'