name             'cron-jobs'
maintainer       'Ride Share Market'
maintainer_email 'systemsadmin@ridesharemarket.com'
license          'All rights reserved'
description      'Installs/Configures cron-jobs'
long_description 'Installs/Configures cron-jobs'
version          '0.1.0'
