global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these extra labels to all timeseries collected by this Prometheus instance.
  labels:
    monitor: 'rsm-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'node'
    target_groups:
      - targets: ['rsm-node-exporter:9100']

  - job_name: 'docker'
    target_groups:
      - targets: ['rsm-container-exporter:9104']

  - job_name: 'statsd'
    target_groups:
      - targets: ['rsm-statsd-bridge:9102']
