name             'docker-grafana'
maintainer       'Ride Share Market'
maintainer_email 'systemsadmin@ridesharemarket.com'
license          'All rights reserved'
description      'Installs/Configures docker-grafana'
long_description 'Installs/Configures docker-grafana'
version          '1.0.0'

depends 'git'
depends 'docker'
